parameters:
- name: regressionTests
  type: object
  default:
  - name: MSTestExample-Attachments
    format: mstest
    testResultsFile: '$(Build.SourcesDirectory)/examples/dotnet/MSTestExample-Attachments/TestResults/TestResults.trx'
  - name: NUnitExample
    format: nunit
    testResultsFile: '$(Build.SourcesDirectory)/examples/dotnet/NUnitExample/TestResults/TestResults.xml'
  - name: NUnitExample-Attachments
    format: nunit
    testResultsFile: '$(Build.SourcesDirectory)/examples/dotnet/NUnitExample-Attachments/TestResults/TestResults.xml'
  - name: NUnitExample-Attachments-Wildcard
    format: nunit
    testResultsFile: '$(Build.SourcesDirectory)/examples/generated/**/TestResults.xml'
  - name: JUnitExample-Maven
    format: junit
    testResultsFile: '$(Build.SourcesDirectory)/examples/java/JUnitExample-maven/TestResults.xml'
  - name: FailOnFailedTests
    format: nunit
    testResultsFile: '$(Build.SourcesDirectory)/examples/dotnet/NUnitExample/TestResults/TestResults.xml'
    failTaskOnFailedTests: true

steps:
- pwsh: |
    Import-Module $(Build.SourcesDirectory)/examples/helpers/TestGenerator/TestGenerator.psm1
    $items = @(
      @{ Folder = "NUnit-1MB"; TestCases = @( "4852", "4861", "4862"); AttachmentCount = 5; AttachmentSize = (1024*1024)}
      @{ Folder = "NUnit-5MB"; TestCases = @( "4859", "4863", "4864"); AttachmentCount = 5; AttachmentSize = (1024*1024*5)}
      @{ Folder = "NUnit-10MB"; TestCases =@( "4860", "4865", "4866"); AttachmentCount = 5; AttachmentSize = (1024*1024*10)}
    )

    foreach ($item in $items) {
      $invokeArgs = @{
        TestResultsDirectory = "$(Build.SourcesDirectory)/examples/generated/$($item.Folder)"
        TestResultsFile = "TestResults.xml"
        TestFramework = "NUnit"
        TestCaseIds = $item.TestCases
        AttachmentsCount = $item.AttachmentCount
        AttachmentSizeInBytes = $item.AttachmentSize
      }

      Build-TestResults @invokeArgs
    }

  displayName: 'Generate additional test data'


- ${{ each test in parameters.regressiontests }}:
  - task: PowerShell@2
    name: ${{ replace(lower(test.name), '-','_') }}
    displayName: 'Run extension against ${{ test.name }}'
    ${{ if eq(test.failTaskOnFailedTests,'true') }}:
      continueOnError: true
    inputs:
      workingDirectory: $(Pipeline.Workspace)/build
      filePath: '$(Pipeline.Workspace)/build/Test-ExtensionLocally.ps1'
      arguments: >
        -CollectionUri $(System.CollectionUri)
        -ProjectName 'Test Plan Extension'
        -AccessToken $(System.AccessToken)
        -TestResultFormat ${{ test.format }}
        -TestResultFiles ${{ test.testResultsFile }}
        -TestPlan 'Primary Test Plan'
        -TestConfigFilter ''
        -TestConfigAliases ''
        -TestCaseMatchStrategy ''
        -TestCaseProperty 'TestCaseId'
        -TestCaseRegex 'TestCase(\d+)'
        -TestConfigProperty ''
        -TestRunTitle '$(Build.DefinitionName) - $(nodeVersion) - ${{ test.name }}'
        -BuildId $(Build.BuildId)
        -ReleaseId ''
        -ReleaseEnvironmentId ''
        -failTaskOnFailingTests '${{ iif( ne(test.failTaskOnFailedTests,''), test.failTaskOnFailedTests, 'false' ) }}'
        -DryRun ''

  - ${{ if eq(test.failTaskOnFailedTests,'true') }}:
    - task: PowerShell@2
      displayName: 'Check for failed tests in ${{ test.name }}'
      inputs:
        targetType: 'inline'
        script: |
          # obtain the timeline for the current pipeline run
          $auth64 = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$(System.AccessToken)"))
          $headers = @{ Authorization = "Basic $auth64" }
          $url = "$(System.CollectionUri)$(System.TeamProject)/_apis/build/builds/$(Build.BuildId)/timeline?api-version=7.1"
          $timeline = Invoke-RestMethod -Uri $url -Headers $headers

          # obtain the task record for the test execution task
          $task = $timeline.records | Where-Object { $_.parentId -eq '$(System.JobId)' -and $_.refName -eq $env:TASK_NAME }

          # ensure that the outcome of the task was succeededWithIssues
          if ($task.result -ne 'succeededWithIssues') {
            Write-Error "The task $($task.name) did not complete with the expected result of 'succeededWithIssues'. Actual result: $($task.result)"
          }
      env:
        TASK_NAME: ${{ replace(lower(test.name), '-','_') }}
